name: React CI
on:
  push:
    branches:
      - master
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: [ 18.7.0 ]
      - run: yarn install
      - uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx'
          annotations: true

  cypress-run:
    runs-on: ubuntu-20.04
    name: E2E on Chrome
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
         browser: chrome




