name: React CI
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: install
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: eslint:test
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: build
