name: React CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:[18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v1
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: install
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: eslint:test
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: build
