name: React CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      args: eslint:test
      - uses: kingscooty/actions-yarn-cy@master
        with:
          args: build
